name: whide
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cycler=0.10.0
  - cython=0.29.14
  - dbus=1.13.12
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - joblib=0.14.1
  - jpeg=9b
  - kiwisolver=1.0.1
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libllvm8=8.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libstdcxx-ng=9.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - llvm-openmp=9.0.1
  - llvmlite=0.31.0
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - ncurses=6.1
  - numba=0.48.0
  - numpy=1.18.1
  - openssl=1.1.1d
  - pandas=1.0.1
  - pcre=8.43
  - pip=20.0.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pytables=3.6.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2019.3
  - qt=5.9.7
  - readline=8.0
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - setuptools=46.0.0
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.30.1
  - tk=8.6.10
  - tornado=6.0.4
  - umap-learn=0.3.10
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11

